# importing required libraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as exp

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
from sklearn import svm

# Data Collection

In [ ]:
#dataset0 = pd.read_csv("/content/cancer.csv") # importing csv from local drive

import dataset using sklearn datasets..

In [ ]:
import sklearn.datasets

In [ ]:
df0 = sklearn.datasets.load_breast_cancer() # datasets in sklearn library for learning

In [ ]:
print(df0)

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
 

In [ ]:
type(df0)

sklearn.utils.Bunch

In [ ]:
dataset = pd.DataFrame(df0.data, columns = df0.feature_names)

In [ ]:
dataset.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [ ]:
#checking dataset features/variables
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

In [ ]:
#inserting target/predicted variable in first location
dataset.insert(0,column='diagnosis', value=df0.target)

In [ ]:
dataset["diagnosis"].value_counts()

1    357
0    212
Name: diagnosis, dtype: int64

from dataset, 
1 - Benign
0 - Malignant 

In [ ]:
# getting mean value of variables for each target/type
dataset.groupby('diagnosis').mean()

mean radius  mean texture  mean perimeter   mean area  \
diagnosis                                                          
0            17.462830     21.604906      115.365377  978.376415   
1            12.146524     17.914762       78.075406  462.790196   

           mean smoothness  mean compactness  mean concavity  \
diagnosis                                                      
0                 0.102898          0.145188        0.160775   
1                 0.092478          0.080085        0.046058   

           mean concave points  mean symmetry  mean fractal dimension  ...  \
diagnosis                                                              ...   
0                     0.087990       0.192909                0.062680  ...   
1                     0.025717       0.174186                0.062867  ...   

           worst radius  worst texture  worst perimeter   worst area  \
diagnosis                                                              
0             21.134811      29.318208       141.370330  1422.286321   
1             13.379801      23.515070        87.005938   558.899440   

           worst smoothness  worst compactness  worst concavity  \
diagnosis                                                         
0                  0.144845           0.374824         0.450606   
1                  0.124959           0.182673         0.166238   

           worst concave points  worst symmetry  worst fractal dimension  
diagnosis                                                                 
0                      0.182237        0.323468                 0.091530  
1                      0.074444        0.270246                 0.079442  

[2 rows x 30 columns]

Analysis - values of features in Malignant are comparatively higher than Bening

# Separating independent variables and target

In [ ]:
X = dataset.drop('diagnosis', axis = 1)
Y = dataset['diagnosis']

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   diagnosis                569 non-null    int64  
 1   mean radius              569 non-null    float64
 2   mean texture             569 non-null    float64
 3   mean perimeter           569 non-null    float64
 4   mean area                569 non-null    float64
 5   mean smoothness          569 non-null    float64
 6   mean compactness         569 non-null    float64
 7   mean concavity           569 non-null    float64
 8   mean concave points      569 non-null    float64
 9   mean symmetry            569 non-null    float64
 10  mean fractal dimension   569 non-null    float64
 11  radius error             569 non-null    float64
 12  texture error            569 non-null    float64
 13  perimeter error          569 non-null    float64
 14  area error               5

In [ ]:
import seaborn as sns

In [ ]:
X1 = X.iloc[:,:10]

In [ ]:
X1.insert(0, value=dataset['diagnosis'], column='Diagnosis')

In [ ]:
X1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Diagnosis               569 non-null    int64  
 1   mean radius             569 non-null    float64
 2   mean texture            569 non-null    float64
 3   mean perimeter          569 non-null    float64
 4   mean area               569 non-null    float64
 5   mean smoothness         569 non-null    float64
 6   mean compactness        569 non-null    float64
 7   mean concavity          569 non-null    float64
 8   mean concave points     569 non-null    float64
 9   mean symmetry           569 non-null    float64
 10  mean fractal dimension  569 non-null    float64
dtypes: float64(10), int64(1)
memory usage: 49.0 KB


# Splitting data into train and test

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, train_size=0.75, random_state=2)

In [ ]:
print(X.shape, X_train.shape, X_test.shape)

(569, 30) (426, 30) (143, 30)


# Model Training - SVM

In [ ]:
from sklearn import svm

In [ ]:
model = svm.SVC(kernel = 'linear')

In [ ]:
model_new = model.fit(X_train, Y_train)

In [ ]:
model_new

SVC(kernel='linear')

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
y_pred

In [ ]:
accuracy_score(y_pred, Y_test)

0.951048951048951

In [ ]:
y_pred = model.predict(X_train)

In [ ]:
accuracy_score(Y_train, y_pred)

0.9671361502347418

# Model Evaluation

Accuracy Score

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(Y_train, X_train_prediction)

In [ ]:
print('Accuracy on training data=',training_data_accuracy)

Accuracy on training data= 0.9671361502347418


In [ ]:
# accuracy on training data
X_test_prediction = model.predict(X_test)
testing_data_accuracy = accuracy_score(Y_test, X_test_prediction)

In [ ]:
print('Accuracy on testing data=',testing_data_accuracy)

Accuracy on testing data= 0.951048951048951


# Confusion Matrix

In [ ]:
cm = confusion_matrix(Y_train, y_pred)
print(cm)

[[147   9]
 [  5 265]]


In [ ]:
accuracy1=(cm[0,0]+cm[1,1])/cm.sum()
print ('Accuracy : ', accuracy1)

sensitivity1 = cm[0,0]/(cm[0,0]+cm[0,1])
print('Sensitivity : ', sensitivity1 )

specificity1 = cm[1,1]/(cm[1,0]+cm[1,1])
print('Specificity : ', specificity1)

Accuracy :  0.9671361502347418
Sensitivity :  0.9423076923076923
Specificity :  0.9814814814814815


In [ ]:
from sklearn.metrics import classification_report

In [ ]:
report = classification_report(Y_train, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.97      0.94      0.95       156
           1       0.97      0.98      0.97       270

    accuracy                           0.97       426
   macro avg       0.97      0.96      0.96       426
weighted avg       0.97      0.97      0.97       426



# Building Predictive System

In [ ]:
input_data = (13.54,14.36,87.46,566.3,0.09779,0.08129,0.06664,0.04781,0.1885,0.05766,0.2699,0.7886,2.058,23.56,0.008462,0.0146,0.02387,0.01315,0.0198,0.0023,15.11,19.26,99.7,711.2,0.144,0.1773,0.239,0.1288,0.2977,0.07259)

In [ ]:
# change the input data to a numpy array
input_data_np = np.asarray(input_data)

In [ ]:
# reshape the array as we are predicting for one datapoint
input_reshape = input_data_np.reshape(1,-1) # to make it as one datapoint

In [ ]:
input_reshape

array([[1.354e+01, 1.436e+01, 8.746e+01, 5.663e+02, 9.779e-02, 8.129e-02,
        6.664e-02, 4.781e-02, 1.885e-01, 5.766e-02, 2.699e-01, 7.886e-01,
        2.058e+00, 2.356e+01, 8.462e-03, 1.460e-02, 2.387e-02, 1.315e-02,
        1.980e-02, 2.300e-03, 1.511e+01, 1.926e+01, 9.970e+01, 7.112e+02,
        1.440e-01, 1.773e-01, 2.390e-01, 1.288e-01, 2.977e-01, 7.259e-02]])

In [ ]:
input_data_np

array([1.354e+01, 1.436e+01, 8.746e+01, 5.663e+02, 9.779e-02, 8.129e-02,
       6.664e-02, 4.781e-02, 1.885e-01, 5.766e-02, 2.699e-01, 7.886e-01,
       2.058e+00, 2.356e+01, 8.462e-03, 1.460e-02, 2.387e-02, 1.315e-02,
       1.980e-02, 2.300e-03, 1.511e+01, 1.926e+01, 9.970e+01, 7.112e+02,
       1.440e-01, 1.773e-01, 2.390e-01, 1.288e-01, 2.977e-01, 7.259e-02])

In [ ]:
prediction = model.predict(input_reshape)
print(prediction) # output is 0, 0 means malignant or 1 represents benign

[1]


/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


In [ ]:
# if the array of values changed, the ouut will be displayed as 0 or 1

# Hyper parameter Tuning

In [ ]:
# Using GridsearchCV, tuning the parameters to find the best parameters for better accuracy

In [ ]:
help(svm.SVC) # here kernel have 4 types, degree of polynomial varies, class weight have 'dict' or 'balanced, 

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
param_grid = {'kernel':['rbf', 'poly', 'sigmoid', 'linear'], 'degree':[1,2,3,4,5], 'C':[0.1, 1, 100, 1000]}
grid = GridSearchCV(svm.SVC(), param_grid)
grid.fit(X_train, Y_train)

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 100, 1000], 'degree': [1, 2, 3, 4, 5],
                         'kernel': ['rbf', 'poly', 'sigmoid', 'linear']})

In [ ]:
print(grid.best_params_)
print(grid.score(X_test, Y_test))

{'C': 1000, 'degree': 1, 'kernel': 'rbf'}
0.958041958041958


In [ ]:
print(grid.best_params_)
print(grid.score(X_train, Y_train))

{'C': 1000, 'degree': 1, 'kernel': 'rbf'}
0.9624413145539906


from the above result, hyperparameters: kernel as RBF, C value is 1000, and degree of polynomial is 1 to get max accuracy